#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch="main"
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $current_branch = $protected_branch ]; then
  echo "❌ Direct push to $protected_branch branch is not allowed"
  echo "Please create a pull request instead"
  exit 1
fi

bash -c 'branch="$(git rev-parse --abbrev-ref HEAD)"; if [ "$branch" = "main" ]; then echo "❌ Direct push to main branch is not allowed. Please create a pull request instead."; exit 1; fi'